const state={theme:localStorage.getItem('theme')||'Ocean',persona:localStorage.getItem('persona')||'Chaitanya',name:localStorage.getItem('name')||'',honorific:localStorage.getItem('honorific')||'Boss'};
const el=(id)=>document.getElementById(id);
el('themeName').textContent=state.theme;el('footTheme').textContent=state.theme;el('personaInline').textContent=state.persona;el('personaLabel').textContent=state.persona;el('name').value=state.name;el('honorific').value=state.honorific;el('persona').value=state.persona;
el('btnTheme').onclick=()=>{const themes=['Ocean','Dark','Light','Neon'];const idx=(themes.indexOf(state.theme)+1)%themes.length;state.theme=themes[idx];localStorage.setItem('theme',state.theme);el('themeName').textContent=state.theme;el('footTheme').textContent=state.theme;document.body.style.setProperty('--accent',state.theme==='Neon'?'#ff00e5':(state.theme==='Light'?'#0077ff':'#00d4ff'));};
el('btnSaveProfile').onclick=()=>{state.name=el('name').value.trim();state.honorific=el('honorific').value;state.persona=el('persona').value;localStorage.setItem('name',state.name);localStorage.setItem('honorific',state.honorific);localStorage.setItem('persona',state.persona);el('personaInline').textContent=state.persona;el('personaLabel').textContent=state.persona;toast(`Profile saved. Hello ${state.honorific}${state.name? ' ' + state.name : ''}!`);};
const holo=document.getElementById('holo');const ctx=holo.getContext('2d');let t=0;function drawHolo(){const w=holo.width,h=holo.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(0,200,255,0.08)';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(0,200,255,0.8)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(w/2,h/2-10,80,0,Math.PI*2);ctx.stroke();for(let i=0;i<12;i++){const y=(i*16+(t%16))%h;ctx.fillStyle='rgba(0,200,255,0.15)';ctx.fillRect(0,y,w,2);}t+=1;requestAnimationFrame(drawHolo);}drawHolo();
function answerQuestion(q){q=q.toLowerCase().trim();const who=`${state.persona}`;if(!q)return'Please type a question.';if(q.includes('weather'))return'Use the Weather widget on the left—auto-detects your location.';if(q.includes('your name')||q.includes('who are you'))return`I am ${who}, your AI assistant.`;if(q.includes('jarvis')){state.persona='Jarvis';localStorage.setItem('persona','Jarvis');el('personaInline').textContent='Jarvis';el('personaLabel').textContent='Jarvis';return'Switched persona to Jarvis.';}if(q.includes('chaitanya')){state.persona='Chaitanya';localStorage.setItem('persona','Chaitanya');el('personaInline').textContent='Chaitanya';el('personaLabel').textContent='Chaitanya';return'Calm wisdom mode activated.';}if(q.match(/\d+[\s\+\-\*\/\%\^\(\)\d\s]+/)){try{return eval(q).toString();}catch(e){return'Could not compute.';}}return`(${who}) I will improve this knowledge engine in Phase 2/online mode. For now, try "weather", "switch to Jarvis", or a math expression.`;}
el('btnAsk').onclick=()=>{const q=el('q').value;const text=answerQuestion(q);el('answer').innerHTML=text;};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const r=new SR();r.lang='en-IN';r.interimResults=false;r.maxAlternatives=1;el('btnMic').onclick=()=>{r.start();el('micHint').textContent='Listening…';};r.onresult=(ev)=>{const said=ev.results[0][0].transcript;el('q').value=said;el('answer').innerHTML=answerQuestion(said);el('micHint').textContent='Heard: '+said;};r.onend=()=>{setTimeout(()=>el('micHint').textContent='Say a command.',1000);}}else{el('micHint').textContent='Voice unavailable in this browser.';}
document.querySelectorAll('.launcher').forEach(btn=>{btn.addEventListener('click',()=>{const app=btn.dataset.app;toast(app==='pdf'?'Export will download visible answer as PDF soon.':`Launching ${app} (demo)`);});});
const adapterList=JSON.parse(localStorage.getItem('adapters')||'[]');renderAdapters();function renderAdapters(){const ul=document.getElementById('adapterList');ul.innerHTML='';adapterList.forEach((u,i)=>{const li=document.createElement('li');li.textContent=u;const x=document.createElement('button');x.textContent='×';x.className='chip';x.style.marginLeft='8px';x.onclick=()=>{adapterList.splice(i,1);localStorage.setItem('adapters',JSON.stringify(adapterList));renderAdapters();};li.appendChild(x);ul.appendChild(li);});}
document.getElementById('btnScan').onclick=()=>{const url=document.getElementById('adapterUrl').value.trim();if(!url)return toast('Please paste a URL.');adapterList.push(url);localStorage.setItem('adapters',JSON.stringify(adapterList));renderAdapters();document.getElementById('adapterUrl').value='';toast('Adapter added locally (demo).');};
async function loadWeather(){try{if(!navigator.geolocation){el('weatherText').textContent='—';return;}navigator.geolocation.getCurrentPosition(async(pos)=>{const {latitude,longitude}=pos.coords;const url=`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code`;const res=await fetch(url);const data=await res.json();const temp=data?.current?.temperature_2m;el('weatherText').textContent=`${temp ?? '--'}°C`;},()=>{el('weatherText').textContent='Location blocked';});}catch(e){el('weatherText').textContent='—';}}loadWeather();
document.getElementById('toolPDF').onclick=()=>{const blob=new Blob([document.getElementById('answer').innerText],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='answer.txt';a.click();};
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.classList.add('show'),10);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),300)},2200);}const s=document.createElement('style');s.textContent=`.toast{position:fixed;left:50%;transform:translateX(-50%);bottom:-40px;background:rgba(0,0,0,.7);color:#fff;padding:10px 14px;border-radius:10px;border:1px solid rgba(80,170,255,.4);transition:all .3s}.toast.show{bottom:16px}`;document.head.appendChild(s);
